### ISSUE TITLE
Object:requestOptions不知道怎么使用

### ISSUE THREAD

**Issue by fanly** [marchFantasy/vue-file-upload#1]
@param {Object:requestOptions} [请求附加参数:  formData:{},headers:{},responseType:'json',withCredentials:false]
这个参数怎么传进去呢？我试了试貌似不管用，能提供下demo吗？
我的：
requestOptions:{
        headers: {
          demo:'yemeishu',
          Origin: 'https://wx.qq.com'
        },
        formData: {
          webwx_data_ticket:'AQfqbTaaJaVhba7t1qqXpsno'
        },
        responseType:'json',
        withCredentials:false
      },

**Comment by marchFantasy** [comment]
0.0.3已经修改了！你这样的写法没问题的，示例代码也有了
