### ISSUE TITLE
可以显示图片预览吗？

### ISSUE THREAD

**Issue by docikaci** [marchFantasy/vue-file-upload#10]
在下有2个问题：多谢回答
1. 可以显示图片预览吗？
2. 支持上传进度吗？
非常感谢！

PS: 这里没有服务器不方便测试。

**Comment by marchFantasy** [comment]
上传进度和预览都支持的，预览的话具体需要你自己写额外预览的代码；
上传文件会返回给相应的回调函数里！
@docikaci
