### ISSUE TITLE
可否增加一个函数用于重置组件状态

### ISSUE THREAD

**Issue by huhk-sysu** [marchFantasy/vue-file-upload#13]
问题主要是我使用的时候没有destroy的过程导致他不会自动清空队列。挨个调用remove()好像太麻烦了。
看源码发现原来类里已经提供了这样一个方法，于是就直接调用了。

另外还有一个问题是：你的组件监听input的change事件来更新文件队列。当我选择了一个文件加入，再用remove方法把它从队列中清除后，input的value没有改变，导致无法再次选择这个文件来把它添加到队列中。这个问题在demo里就存在。

目前的解决方案是添加以下两行手动重置组件状态：
``` javascript
this.$refs.uploader.$refs.fileInput.value = '';
this.$refs.uploader.fileUploader.clearQueue();
```
按理说我不该直接操作组件里封装的内容的，希望能添加一个重置的方法。

**Comment by marchFantasy** [comment]
@huhk-sysu,以提供清空列表接口，上传文件，每次默认重置input的值！
谢谢您的关注，最近项目太忙了，所以注意！
 [1b18515](https://github.com/marchFantasy/vue-file-upload/commit/1b185153fd13cf4557c1516eda03d130e72424d1)
