### ISSUE TITLE
如何做到预览功能

### ISSUE THREAD

**Issue by TomatoesSir** [marchFantasy/vue-file-upload#15]
不知道作者的这个 现在版本是否可以预览

**Comment by TomatoesSir** [comment]
作者麻烦帮我解答一下呀  在线等急等

**Comment by marchFantasy** [comment]
@TomatoesSir  不知道你要的预览具体是什么场景！
现在demo里，上传的图片已经可以预览了，还没有提交到后台！不知道这个算不算预览

**Comment by TomatoesSir** [comment]
现在版本就可以预览了么 就是在提交到后台之前预览 我看看demo

**Comment by TomatoesSir** [comment]
没有呀  只能做到预览名称之类的 怎么生成图片呢 我用FileReader 没有成功

**Comment by TomatoesSir** [comment]
谢谢作者了  弄好了

**Comment by marchFantasy** [comment]
ok
