### ISSUE TITLE
上传完成后，能接收服务器返回的信息么？

### ISSUE THREAD

**Issue by lazybeancn** [marchFantasy/vue-file-upload#17]
上传完成后我要获取返回的一个值，能实现么？

**Comment by marchFantasy** [comment]
```javascript
events:{
      type:Object,
      default:()=>{
        return {
          onProgressUpload:noop,
          onCompleteUpload:noop,
          onErrorUpload:noop,
          onSuccessUpload:noop,
          onAbortUpload:noop,
          onAddFileFail:noop,
          onAddFileSuccess:noop
        }
      }
    }
```
这里都有，绑定:events

**Comment by iverson3** [comment]
你好，我绑定了events，但是回调函数里面response变量一直是null  没有数据？？ 怎么回事

> onErrorUpload: (file,response,status,headers) => {
                        console.log(file)
                        console.log(response)
                        console.log(status)
                        console.log(headers)
                        console.log('upload failed')
                    }, 
                    onSuccessUpload: (file,response,status,headers) => {
                        console.log(file)
                        console.log(response)
                        console.log(status)
                        console.log(headers)
                        console.log('upload success')
                    },

**Comment by marchFantasy** [comment]
你可以用工具看看是不是真的有返回数据？

**Comment by iverson3** [comment]
肯定是有数据返回的，这个处理文件上传的api是经过其他上传组件测试过了的，返回数据没问题，返回的是json格式的；  而且就算我改接口让它直接返回一个字符串 在回调函数中也是接受不到这个返回的！ 无奈啊

**Comment by marchFantasy** [comment]
可以把相关netwok 请求、输出数据截图放出来吗？

**Comment by iverson3** [comment]
![](http://ww1.sinaimg.cn/large/5e06b5b0gy1fss6l9gr27j20xa0783yf.jpg)
![](http://ww1.sinaimg.cn/large/5e06b5b0gy1fss6lg0btaj20p10e8t8z.jpg)
![](http://ww1.sinaimg.cn/large/5e06b5b0gy1fss6lmz8v5j211i0caq3n.jpg)

**Comment by iverson3** [comment]
问题终于解决了！  原来是因为我没有设置response header：

> headers: {
                        'Accept': 'application/json'
                    }
