### ISSUE TITLE
为什么我设置了withCredentials:true,但是请求的时候任然带不上cookies

### ISSUE THREAD

**Issue by wqzwh** [marchFantasy/vue-file-upload#18]
为什么我设置了withCredentials:true,但是请求的时候任然带不上cookies

求助解答

**Comment by marchFantasy** [comment]
@wqzwh ，这个参数是适合跨域请求带上cookie，服务端也要做相应配置的；
在同一个站点下使用withCredentials属性是无效的
参考：[链接](https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/withCredentials)
