### ISSUE TITLE
some picture can't upload in wechat

### ISSUE THREAD

**Issue by pzuopin** [marchFantasy/vue-file-upload#20]
I have find some picture can't upload in wechat(android)， the netWork express  that wechat can't correct load some picture because  lack of "base 64".
I don't know how to resolve  the problem in vue-file-upload ----

and thanks your code(Maybe I should use Chinese  to express)

**Comment by marchFantasy** [comment]
maybe its not support syntax:  window.URL.createObjectURL(file.file)

**Comment by marchFantasy** [comment]
You can use the url returned by the server after uploading the picture

**Comment by pzuopin** [comment]
Thank you very much for taking time to help me solve the problem !!!

Vue-file-upload working properly when it used in other scenes, but it can not work normally in WeChat(android) , some picture loading did not respond(I test in huawei P9 、hauwei mate 7). The picture is taken locally from the phone, and Vue-file-upload error like: 
Filters: false 

非常感谢你能抽时间帮忙解决我的问题！！！
Vue-file-upload正常工作（使用其他访问方式），但是使用安卓微信浏览器访问时（华为P9、华为mate7），部分图片（一些图片可以正常加载上传）从手机本地获取失败，报错如下：
 filters返回为false,  图片过滤判断为失败，图片类型为空

onAddFileFail：

File {name: "image%3A148818", lastModified: 1477705190000, lastModifiedDate: Sat Oct 29 2016 09:39:50 GMT+0800 (CST), webkitRelativePath: "", size: 389071…}
lastModified:1477705190000
name:"image%3A148818"
size:389071
type:""
webkitRelativePath:""

**Comment by marchFantasy** [comment]
很明显，这些手机本地图片的扩展名没有了，所以你的函数onAddFileFail无法正常过滤了。
缺少这个字段：type:"image/jpeg"

**Comment by pzuopin** [comment]
感谢可以用中文   哈哈， 安卓微信部分图片可以正常上传的 ，但是有些不能，没反应，确实是没有type:"image/jpeg"，网上说是微信图片识别时少base64 不知道怎么解决  846849713 这是我的QQ

**Comment by marchFantasy** [comment]
我对微信安卓不是很了解，帮不到你！抱歉

**Comment by pzuopin** [comment]
还是很谢谢你！ 对这个图片上传不是很懂，我会继续学习，看看 是不是我自己操作有问题（我是菜鸟），前端东西好多
