### ISSUE TITLE
多个上传按钮，是共用一个FileList么？

### ISSUE THREAD

**Issue by qianniuc** [marchFantasy/vue-file-upload#22]
多个上传按钮，是共用一个FileList么？
我看源码(src/vue-file-upload.vue)里是这样写的
```html
<input ref="fileInput" type="file" name="file">
```
```js
var elTargetFiles = _.isHTML5() ? this.$refs.fileInput.files :this.$refs.fileInput;
```
这个ref是写死的，那多个按钮就是调用的就是同一个fileInput，拿到的就是同一个文件列表？能不能把不同按钮的FileList分割开？？

**Comment by marchFantasy** [comment]
@qianniuc ，那可以使用两个vue-file-upload 组件就可以了啊，就两个按钮分别对应两个上传列表了

**Comment by qianniuc** [comment]
@marchFantasy 用的就是两个vue-file-upload组件，有两个按钮，点击一个上传后，再点击另一个上传，这个后点击的会把前一个的上传的文件都展示出来了

**Comment by marchFantasy** [comment]
按钮是上传所有图片还是上传某一个图片？
上传所有图片可能需要绑定不同的函数的，上传完回调处理也要不一样

**Comment by qianniuc** [comment]
![Uploading 2017-04-21 11.41.22.gif…]()

**Comment by qianniuc** [comment]
![http://7xlm9s.com1.z0.glb.clouddn.com/2017-04-21%2011.41.22.gif](http://7xlm9s.com1.z0.glb.clouddn.com/2017-04-21%2011.41.22.gif)
目前就是这么个情况，上传logo后，再上传图片，那个logo的进度也显示出来了，上传logo和长传图片是两个按钮

**Comment by marchFantasy** [comment]
这个动态图片看不出来什么，一闪而过！我觉得可能你的代码没有控制好进度，共享了进度的数据

**Comment by qianniuc** [comment]
```js
export default {
  method:"POST",
  queue:[],
  alias:"file",
  autoUpload:true,
  filters:[],
  formData:{},
  headers:{},
  maxItems:Number.MAX_VALUE,
  withCredentials:false,
  responseType:"json"
};
```
我发现这个queue好像是公用的，会不会是这个原因导致的？？

**Comment by marchFantasy** [comment]
@qianniuc ,你说的这个bug确实存在，我马上来修复下，稍后更新下。感谢🙏

**Comment by marchFantasy** [comment]
@qianniuc ,已经更新了！谢谢 #23
