### ISSUE TITLE
上传完成后，我怎么重新上传

### ISSUE THREAD

**Issue by shijunti19** [marchFantasy/vue-file-upload#25]
我文件上传成功了，队列结束了，
然后我又把图片删除了（图片即使上传的）从files数组里删除，怎么再重新上传图片，我选择了文件没反应
源代码this.fileUploader.clearQueue()清除队列的，没发现重置的
请教下怎么处理

**Comment by marchFantasy** [comment]
@shijunti19 ,不需要重置的！用的什么系统和浏览器

**Comment by shijunti19** [comment]
@marchFantasy 好了我解决了，我把图标列表封装到vue-file-upload.vue导致出问题，我又改回来了，就正常了
