### ISSUE TITLE
想知道兼容IE9吗，还是要支持formData

### ISSUE THREAD

**Issue by yjjn** [marchFantasy/vue-file-upload#3]
兼容性如何。

**Comment by marchFantasy** [comment]
@yjjn ，IE9好像不支持formdata，所以会模拟表单提交！应该没问题的，有问题可以提

**Comment by yjjn** [comment]
谢谢。试用一下，目前的版本项目里面用的formData 不支持ie9.所以想看看有支持ie9的没有。
