### ISSUE TITLE
error when  run dev

### ISSUE THREAD

**Issue by lei2231** [marchFantasy/vue-file-upload#32]
hi, 
   when i run your project, error exist, can you help me fix this issue ?? thanks ~

$ npm run dev

> vue-file-upload@0.1.2 dev F:\vue\loadfile1\vue-file-upload
> webpack-dev-server --hot --inline --content-base ./demo

'webpack-dev-server' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-file-upload@0.1.2 dev: `webpack-dev-server --hot --inline --content-base ./demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-file-upload@0.1.2 dev script 'webpack-dev-server --hot --inline --content-base ./demo'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-file-upload package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --content-base ./demo
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-file-upload
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-file-upload
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\vue\loadfile1\vue-file-upload\npm-debug.log

**Comment by marchFantasy** [comment]
@lei2231 ,先确保你的node.js环境配置没问题，先 npm install；
