### ISSUE TITLE
reqopts 里 formData 参数，“上传所有文件”的时候，每个文件上传都需要配置一个 key 而且 key 值不同，请问如何设置？

### ISSUE THREAD

**Issue by cag2050** [marchFantasy/vue-file-upload#33]
reqopts 里 formData 参数，“上传所有文件”的时候，每个文件上传都需要配置一个 key 而且 key 值不同，请问如何设置？
在七牛上传时，遇到的这个场景需求。项目例子地址：https://github.com/cag2050/vue_file_upload_demo

**Comment by marchFantasy** [comment]
@cag2050 ,最近因为自己的项目原因一直没回复，十分抱歉！但是像你这种场景最后fork我的代码，然后再进行修改下，加上token就可以了
