### ISSUE TITLE
在苹果上使用时，上传不了视频

### ISSUE THREAD

**Issue by JoeLucky** [marchFantasy/vue-file-upload#36]
我自己写了个简单的上传demo是可以上传的。 用这个库上传不了，查了好久 不知道哪里出问题了。

再次确认了下 不是库导致的 是multiple导致的。当multiple为true时，无法上传视频

**Comment by marchFantasy** [comment]
是ios吗？现在问题解决了吗？

**Comment by JoeLucky** [comment]
@marchFantasy  不是这个组件的问题。是 苹果+微信端 共同导致了 不能批量选择视频。我目前的方案图片多选、视频单选 做2个 vue-file-upload模块

**Comment by sijinglei** [comment]
直接拿手机拍照的视频上传没反应？有遇到过的吗？
