### ISSUE TITLE
因为用到加载条，怎么捕捉上传加载条进度信息？

### ISSUE THREAD

**Issue by Foreverofh** [marchFantasy/vue-file-upload#39]

**Comment by Foreverofh** [comment]
@marchFantasy  进度条已上传就变成100%，怎么没有扑捉到从0到100的过程！

**Comment by marchFantasy** [comment]
可以试着上传一个大一点的文件，小文件速度可能非常快！

**Comment by Foreverofh** [comment]
@marchFantasy  不是大不大的问题，就手机图片，每一次一上传就100%，你有测试过吗？

**Comment by Foreverofh** [comment]
@marchFantasy 我还是一上传变了100%，之后上传成功字体好久才显示！！

**Comment by marchFantasy** [comment]
@Foreverofh ,我自己用safari，火狐，chrome都测试过，上传进度的回调都显示没问题，只不过很快，立马就到100了，所以如果你如果需要显示过程，最好自己加上动画效果
![image](https://user-images.githubusercontent.com/3906826/29597182-878b8986-87f3-11e7-9353-131385015cb5.png)
我上传的首先到48%，然后到100%

**Comment by Foreverofh** [comment]
@marchFantasy 你是手机端吗？ 你上传回调是onProgressUpload这个事件吗?

**Comment by marchFantasy** [comment]
我这边模拟了手机设备，就是onProgressUpload事件
