### ISSUE TITLE
自动上传成功后,index是NaN，搞得我不能把成功地址赋值上去图片上 

### ISSUE THREAD

**Issue by Foreverofh** [marchFantasy/vue-file-upload#41]
![image](https://user-images.githubusercontent.com/15324717/30422973-04942e56-9974-11e7-9312-083d346d7af0.png)

**Comment by Foreverofh** [comment]
@marchFantasy  能解决吗？

**Comment by marchFantasy** [comment]
@Foreverofh ,马上 修复下

**Comment by marchFantasy** [comment]
[3c2ea](https://github.com/marchFantasy/vue-file-upload/commit/3c2ea11a675e9e99bb3758ea7e727fdc0707c3ec)
0.1.4最新版本解决饿了
