### ISSUE TITLE
Option to change style and set custom class

### ISSUE THREAD

**Issue by elciok** [marchFantasy/vue-file-upload#45]
It would be nice to be able to change how the file button looks, instead of always using the default green button set by CSS inside the Vue component. I'd suggest not setting style in the component file and adding a prop to add custom classes to the input file tag.
Other than that, you did a great job. This is the best Vue file upload component I've tried. Sorry I don't speak chinese.

**Comment by marchFantasy** [comment]
thanks, i have fixed it;[d003b1](https://github.com/marchFantasy/vue-file-upload/commit/d003b177e60310cfe961a7fda011791072a12665)
