### ISSUE TITLE
想了解一下，浏览器的支持情况

### ISSUE THREAD

**Issue by DarkRake** [marchFantasy/vue-file-upload#52]
您好！项目中原先使用的AjaxFileUpload，但是发现在IE9里面无法携带自定义的header参数(spring security的安全校验)，导致了再IE9里面文件上传被服务端当成了未授权操作。
看到您这个vue插件，想了解一下兼容性问题

**Comment by marchFantasy** [comment]
支持ie9；vue 的兼容性一致
