### ISSUE TITLE
IE 9 File is not defined

### ISSUE THREAD

**Issue by JasonGaoG** [marchFantasy/vue-file-upload#56]
It said File is not defined when I upload on IE 9.

**Comment by marchFantasy** [comment]
能把具体的错误信息贴出来吗？
@JasonGaoG

**Comment by JasonGaoG** [comment]
SCRIPT5009: “File”未定义 
我是在IE 11 下面选择IE9模式，然后选择文件上传的。

**Comment by marchFantasy** [comment]
已经修复了；[#142d7ea](https://github.com/marchFantasy/vue-file-upload/commit/142d7eab8bc04b5de436c1e6a0628e0a9301c1d7)

**Comment by JasonGaoG** [comment]
@marchFantasy 你好，修复了但是IE9上上传文件还是有问题，你那边测试的可以？

**Comment by marchFantasy** [comment]
@JasonGaoG , 更新到0.1.9版本，试试！我测试过了；不要加filter过滤函数

**Comment by JasonGaoG** [comment]
@marchFantasy  好了，谢谢啊
