### ISSUE TITLE
单个文件上传的时候，有时候file.upload没法继续触发

### ISSUE THREAD

**Issue by hasbug** [marchFantasy/vue-file-upload#59]
在单传的时候，如果上一张还没传完，我立刻选择下一张（选完后我触发file.upoload），或者不断选多张（动作够快），这时候，只会处理到上传第一张，后面选择的都没有动作，待上传、有办法解决这种吗？
  主要是我们的场景太奇葩啦，没法一次性全部去传。场景大概如下：选完图片，先向后端获取一个上传地址和当前这个图片的重命名，我接下来再传图片的附带参数去修改这些值，改完再触发file.upload....每张图片都需要后端重命名，而且，在这一步，后端那边还要核对上传图片的名字对不对，造成我无法全部改名后再自己批量传。。。无奈。
  
  我感觉批量上传的时候，上传队列时，每一个文件能有一个上传前的方法应该就可以解决，哈哈。

**Comment by marchFantasy** [comment]
@hasbug ,我建议你们可以fork我的项目，自己做定制化开发；
我的这个组件开源出来，是为大多数人免费使用的。
