### ISSUE TITLE
在支持多个上传的前提下，自动上传前能判断出是单个上传还是多个上传吗？

### ISSUE THREAD

**Issue by longtengfei2016** [marchFantasy/vue-file-upload#61]
现在getAll()方法在内部，自动上传的时候，在上传之前，请问，在组件外面能判断是单个还是多个上传吗？

**Comment by marchFantasy** [comment]
@longtengfei2016 ,如果是自动上传肯定是你选择一个文件确定后，就立即上传了，所以肯定是一个一个单个上传的；如果你是点击单个或上传所有按钮，回调函数也是在你自己的组件内部函数里，是可以区分的
