### ISSUE TITLE
大文件上传问题？

### ISSUE THREAD

**Issue by xdwxls** [marchFantasy/vue-file-upload#68]
![image](https://user-images.githubusercontent.com/9478777/37858409-4fc93cca-2f3f-11e8-899d-21df9ef2e631.png)

小的图片看不出问题，稍微大一点(比如7 8兆)就看出问题了，发送请求的时候，报这种警告，感觉像是浏览器卡死的状态。过了一两分钟才上传成功。
这种警告我以前也遇到过，不明白这是什么错，由前端还是后端引起的？我项目中使用的nginx反向代理，不知道跟nginx设置是否也有一定的关系？因为后端说他自己测试上传大文件很快的，所以我就疑惑了，希望大神给个解决办法？？

**Comment by marchFantasy** [comment]
@xdwxls 我觉得7、8M左右的文件肯定是没问题的；可以先跳过nginx反向代理试试，直连的方式，测试看看

**Comment by xdwxls** [comment]
@marchFantasy 我test了一下，跳过nginx  确实没啥问题，但是加上nginx，就有问题，卡顿好久才成功，这个改怎么办？

**Comment by marchFantasy** [comment]
@xdwxls , 应该是nginx的配置问题，是不是限制了上传文件的大小、超时等
