### ISSUE TITLE
ie9下获取不到filename

### ISSUE THREAD

**Issue by reef007** [marchFantasy/vue-file-upload#69]
SCRIPT5007: 无法获取未定义或 null 引用的属性“innerHTML”  （这是控制台报的错）

**Comment by reef007** [comment]
![_15221465202696](https://user-images.githubusercontent.com/11729549/37961962-4aa0707e-31ec-11e8-98a0-bb701a20499f.png)
传过去的文件名获取不到，麻烦给看一下是哪里的问题

**Comment by marchFantasy** [comment]
ie9模拟表单提交，看input 输入框的name和value的值

**Comment by reef007** [comment]
不太明白你的意思，能具体说一下问题所在嘛，插件渲染出来的Input name是默认file, value 页面上显示的就是我上传文件的路径

**Comment by marchFantasy** [comment]
filename没必要关注；只要关注name就可以了，name的值是可以自己传递给这个组件的，也是接口所需要的对应字段名；

**Comment by reef007** [comment]
![_15222229419381](https://user-images.githubusercontent.com/11729549/38015382-2b7fc908-329e-11e8-8022-f42881b84489.png)
那按你这么说，接口报这种错误是接口的问题？

**Comment by marchFantasy** [comment]
看看之前的issues[#56](https://github.com/marchFantasy/vue-file-upload/issues/56)，他也是用的ie9，没问题的；应该和接口有关，可以联调下试试看，或者用其他的浏览器

**Comment by reef007** [comment]
好的，我们在联调一下，多谢啦

**Comment by DaemonYue** [comment]
@reef007 请问您这个问题解决了吗？我的现象是一样的，没有找到原因

**Comment by marchFantasy** [comment]
我刚刚更新了版本0.1.10，修复ie9 的文件上传bug
