### ISSUE TITLE
请问不能上传rar格式文件吗？

### ISSUE THREAD

**Issue by xiaomingdexian** [marchFantasy/vue-file-upload#71]
选择rar或其他不常用的格式会报异常，onAddItem函数不会触发
![de038d85974242c18ffa58722341e434](https://user-images.githubusercontent.com/26076008/38227653-d3944e42-3731-11e8-9c01-0a69201d657f.jpg)

**Comment by marchFantasy** [comment]
是不是加了过滤函数？

**Comment by xiaomingdexian** [comment]
您看看是不是FileAlias类的createFileFromInput方法报错？

**Comment by marchFantasy** [comment]
可以尝试运行源代码里提供的demo，注释掉过滤函数；
可以自己尝试debug，看看filealias 里的value值是不是有问题

**Comment by mrleex** [comment]
@marchFantasy @xiaomingdexian 是由于util/public.js里面的isFile函数导致的，把改函数改成：
return file !== null && !!((window.File && file instanceof window.File) && (file.size >= 0))
就好了，因为对于非常见类型的文件，file.type为空

**Comment by marchFantasy** [comment]
是的，谢谢指正！ie下的确会有问题

**Comment by marchFantasy** [comment]
最新版本已修复 0.1.12
