### ISSUE TITLE
IE9下上传失败

### ISSUE THREAD

**Issue by DaemonYue** [marchFantasy/vue-file-upload#72]
我的代码在IE10以上运行是成功的，但是IE9获取文件失败，没有错误信息，上传的接口参数是这样的
![image](https://user-images.githubusercontent.com/20762173/38300095-790702aa-382e-11e8-8a15-c51232b0fea8.png)
请问这是什么原因呢？
这是我的HTML:
![image](https://user-images.githubusercontent.com/20762173/38300232-de6ffba6-382e-11e8-8938-3d5fc8652c1d.png)
JS:
![image](https://user-images.githubusercontent.com/20762173/38300276-f6f60c10-382e-11e8-9752-a28f8db3a033.png)
![image](https://user-images.githubusercontent.com/20762173/38300292-0141112e-382f-11e8-8934-8205a26664b4.png)
因为项目一定要支持IE9，我自己也尝试找了好久的原因，但是仍旧没解决。

**Comment by marchFantasy** [comment]
ie9模拟的是form表单提交，可以看看这个issue[#69](https://github.com/marchFantasy/vue-file-upload/issues/69)

**Comment by marchFantasy** [comment]
我刚刚更新了版本0.1.10，修复ie9 的文件上传bug
