### ISSUE TITLE
IE下上传问题

### ISSUE THREAD

**Issue by sally2015** [marchFantasy/vue-file-upload#73]
运行demo，http://localhost:6080/， 上传文件，
ie9下error：SCRIPT5: 拒绝访问
ie10：SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。 

并没有修改demo文件
平台：window 8

**Comment by marchFantasy** [comment]
这是跨域导致的问题

**Comment by sally2015** [comment]
@marchFantasy 运行的是你项目中的demo文件为什么会出现跨域呢

**Comment by marchFantasy** [comment]
因为demo里服务端的是php，组件的参数还是需要自己根据环境配置的

**Comment by sally2015** [comment]
同一个文件上传的时候，ie下请求正文content-type是这个类型
![image](https://user-images.githubusercontent.com/14807468/38592817-d7563fbe-3d70-11e8-93bd-3ea649734f04.png)
请求头content-length是406
![image](https://user-images.githubusercontent.com/14807468/38592849-f86f5c1c-3d70-11e8-9fc6-a7a6e6336883.png)
chrome下content-length是24796
![image](https://user-images.githubusercontent.com/14807468/38592862-0f51c348-3d71-11e8-95ab-f5072af1ecc6.png)
content-type是这个
![image](https://user-images.githubusercontent.com/14807468/38592882-27f922d8-3d71-11e8-8f0e-b4b0f41ea1c4.png)
这里应该是有问题的，我用nodejs启了个服务器，chrome正常拿到上传文件，ie下拿不到

**Comment by marchFantasy** [comment]
这里做了兼容ie的处理，ie9以下浏览器，模拟的是表单提交方案，提交的值其实就是input的value值；chrome浏览器是利用ajax 上传文件的；两种方案不一样

**Comment by sally2015** [comment]
对，我的意思是想说正常来说content-length应该是像chrome那样的长度。因为我自己在服务器收不到上传的文件，所以才怀疑是content-length不对才导致的，你那边用php在ie下是能收到文件存储吗

**Comment by marchFantasy** [comment]
我刚刚测试了下，的确有你说的问题，我刚刚更新了版本，v0.1.10,更新下版本试试

**Comment by marchFantasy** [comment]
cloneNode 在复制的时候会丢失input 中value值，导致提交的时候filename始终是空的；

**Comment by sally2015** [comment]
再请教一个问题，`form.appendChild(input);`在appendchild的同时不是会把节点也从原来的节点移除吗，我在自己项目遇到了这个问题，但是你的demo没有问题，看了你的代码好像没有特别做处理，是怎么解决的呢?

**Comment by marchFantasy** [comment]
这个组件好像也有同样的问题；我想一下解决方式

**Comment by sally2015** [comment]
uploader.vm.$refs.fileInput.parentNode.parentNode.appendChild(input);
为什么用的是父节点的父节点去添加，这不是改变了原来的位置了吗

**Comment by marchFantasy** [comment]
其实这个时候input的位置是在form表单里了，所以要再调用一次parentNode，完了之后，input位置等于恢复还原到原来的位置了

**Comment by sally2015** [comment]
我找到`ie9下error：SCRIPT5: 拒绝访问`这个的原因了，不是因为跨域，是因为我在项目中用js主动触发了input的选择file

**Comment by marchFantasy** [comment]
是的，input file 的控件的值是只读属性，不能主动干预它的值的。
