### ISSUE TITLE
IE9上传时提示文件下载？

### ISSUE THREAD

**Issue by mrleex** [marchFantasy/vue-file-upload#78]
在IE9下进行上传，提示文件下载，很奇怪，请问有线索么？提示见下图
![alert](https://user-images.githubusercontent.com/2292217/39035745-b997fac8-44ad-11e8-8901-b69422afc9f2.png)

**Comment by marchFantasy** [comment]
能不能详细描述你的问题？这个文件是你要上传的那个文件还是服务端吐出的文件？
另外请检查目标的url地址是否正确；后台接口是否能正常请求

**Comment by mrleex** [comment]
@marchFantasy 解决了，不是这个组件的问题，是响应头为application/json在IE9下会触发下载。。改成text/html就好了，不好意思，可以关单了~
