### ISSUE TITLE
ie9中报错了

### ISSUE THREAD

**Issue by RedArsenal** [marchFantasy/vue-file-upload#80]
1. 操作系统类型(os),
2. 浏览器类型(browser)，版本号(version)
3. 问题错误信息(error stacks)，可截图(screenshots)
4. 详细的场景描述，重现步骤等
![image](https://user-images.githubusercontent.com/19543358/40466106-919be52a-5f56-11e8-8c61-ef33a53c28cc.png)

**Comment by marchFantasy** [comment]
跨域请求需要服务端进行相关配置
