### ISSUE TITLE
选取文件后仍显示“未选择文件”

### ISSUE THREAD

**Issue by Gigi233** [marchFantasy/vue-file-upload#82]
MacOS编写vue前端
        <vue-file-upload url="up_url" ref="vuefileuploader" :events="cbEvents" :request-options="reqopts" @onAdd="onAddItem">
          <span slot="label"></span>
        </vue-file-upload>
选取文件后onAddFileSuccess的log正常‘success add to queue’，files也确实加上了，但“选取文件”按钮旁显示的仍为“未选择文件”

**Comment by marchFantasy** [comment]
其实你可以参考demo中的样式，优化一下ui就可以了！上传文件后的数据会添加到内存中，不会一直放在input控件上
