### ISSUE TITLE
onPreview 图片预览报错

### ISSUE THREAD

**Issue by Kennersky** [marchFantasy/vue-file-upload#84]
模板：
![image](https://user-images.githubusercontent.com/2129521/41074730-0a3185cc-6a3c-11e8-9f9d-6cb2bf0f8f85.png)

数据：
![image](https://user-images.githubusercontent.com/2129521/41074462-e46aad24-6a3a-11e8-8498-85667f0af942.png)
方法：
![image](https://user-images.githubusercontent.com/2129521/41074504-13199432-6a3b-11e8-82c4-6e3ae85280b3.png)

报错：
![image](https://user-images.githubusercontent.com/2129521/41074752-1fe928ca-6a3c-11e8-866e-ee2e3e7bd53a.png)

**Comment by marchFantasy** [comment]
是不是就是我的demo？这是浏览器兼容性问题。

**Comment by Kennersky** [comment]
@marchFantasy 是的就是按你的demo写的，我浏览器是chrome也不兼容？那要怎么写才能用呢？

**Comment by marchFantasy** [comment]
你修改了template的代码，onPreview(files)，files是数组，这类问题不要提issue了

**Comment by Kennersky** [comment]
@marchFantasy 明白了，要写成file[0].file来读取。谢谢
