### ISSUE TITLE
图片预览只生效一次，再次上传不触发预览事件

### ISSUE THREAD

**Issue by Kennersky** [marchFantasy/vue-file-upload#85]
如题
![tim 20180611165836](https://user-images.githubusercontent.com/2129521/41222359-363c3ada-6d99-11e8-98d1-6fe7336b2045.png)
![image](https://user-images.githubusercontent.com/2129521/41222424-628fe79e-6d99-11e8-9c93-c6db174d193b.png)

![tim 20180611165744](https://user-images.githubusercontent.com/2129521/41222360-39f4f0ea-6d99-11e8-85f7-1d131f9b76f0.png)

**Comment by marchFantasy** [comment]
因为上传了同一张图片，onChange事件无法触发；

**Comment by Kennersky** [comment]
@marchFantasy 不是的，选了不同图片也是一样啊，只执行一次预览，再点一次上传别的图片能上传成功，但预览事件就没有触发了

**Comment by marchFantasy** [comment]
哎。你的onPreview 函数每次都读第一张图片，当然预览不了其他图片
