### ISSUE TITLE
过滤函数里怎么显示回调？比如选择了不符合的文件如何提示给用户

### ISSUE THREAD

**Issue by Kennersky** [marchFantasy/vue-file-upload#87]
你好 @marchFantasy  现在的过滤函数是直接把不符合的选择给忽略了，也就是没有任何提示，也没有执行上传，我如果要指定格式后，然后弹出的文件选择里只有符合的类型才是可选的要怎么处理，就像input file 的accept设置后的效果。或者用户选择了不符合的文件类型给用户一个提示要怎么写？

建议多一个设置accept的参数，可以直接指定file可接收的文件类型

**Comment by marchFantasy** [comment]
我觉得不应该等用户出错的时候给提示，而是一开始就告诉用户可以上传什么类型的文件。
后面我会考虑要不要加上accept
