### ISSUE TITLE
如何设置允许上传的文件的大小？   

### ISSUE THREAD

**Issue by iverson3** [marchFantasy/vue-file-upload#88]
请问，如何设置允许上传的文件的大小？   
我这边图片稍微大一点就上传失败，不知道默认设置的是多少？ 又该如何设置？

**Comment by marchFantasy** [comment]
1.可以先文案提示：上传文件最大多少M；
2.在filters里写个过滤函数

**Comment by iverson3** [comment]
可以给个示例嘛？ 谢谢

**Comment by iverson3** [comment]
> filters: [
                    {
                        name:"imageFilter",
                        fn(file){
                            var type = '|' + file.type.slice(file.type.lastIndexOf('/') + 1) + '|';
                            return '|jpg|png|jpeg|bmp|gif|'.indexOf(type) !== -1;
                        }
                    },
                    {
                        name:"imageFilter2",
                        fn(file) {
                            let size = file.size;
                            return size < 100000000;
                        }
                    }
                ],

这样可以不？
但还是一样上传失败，服务器端获取不到上传文件的数据

服务器端php 输出  $_FILES   结果是：

> Array
(
    [uploadFileObj2] => Array
        (
            [name] => DSCF5285.JPG
            [type] => 
            [tmp_name] => 
            [error] => 1
            [size] => 0
        )

)

**Comment by marchFantasy** [comment]
可以的

**Comment by iverson3** [comment]
像这样子写了过滤函数，还是不行呀  稍微大一点点的图片就会上传失败！ 服务器端获取不到图片数据

**Comment by marchFantasy** [comment]
说明你上传的图片还是太大了。php配置有没有限制上传文件的大小限制？
