### ISSUE TITLE
请问这个demo用的不是 html 模板，用的是什么声明方式

### ISSUE THREAD

**Issue by magicliang** [marchFantasy/vue-file-upload#9]
可以用 html 模板做个 demo 吗？

**Comment by marchFantasy** [comment]
@magicliang ，这是demo上模板翻译过来的
```html
<template>
<vue-file-upload
    url="http://localhost:8000/vue-file-upload/demo/upload.php"
    v-bind:files.sync = 'files'
    v-bind:events = 'cbEvents'
    v-bind:filters = "filters"
    v-bind:request-options = "reqopts"
>
    <button type='button' @click="doPost">上传 </button>
    <table>
        <thead>
             <th>name</th>
             <th>size</th>
             <th>progress</th>
             <th>status</th>
             <th>action</th>
       </thead>
       <tbody>
             <tr v-for='file in files' >
                 <td v-text='file.name'></td>
                 <td v-text='file.size'></td>
                 <td v-text='file.progress'></td>
                 <td v-text='onStatus(file)'></td>
                 <td>
                      <button type='button' value='upload' @click="uploadItem(file)">上传</button>
                 </td> 
             </tr>
       </tbody>
    </table>
    <button type='button' @click="uploadAll">上传所有文件</button>
</vue-file-upload>
</template>
```

**Comment by magicliang** [comment]
谢谢

**Comment by magicliang** [comment]
你好，我根据这个示例和之前的示例写了一个ImagesUploader.vue文件:

- `<template>

  <vue-file-upload
    url="http://localhost:8080/res/v1/image"
    v-bind:files.sync = 'files'
    v-bind:events = 'cbEvents'
    v-bind:filters = "filters"
    v-bind:request-options = "reqopts"
  >
    <button type='button' @click="doPost">上传 </button>
    <table>
      <thead>
      <th>name</th>
      <th>size</th>
      <th>progress</th>
      <th>status</th>
      <th>action</th>
      </thead>
      <tbody>
      <tr v-for='file in files' >
        <td v-text='file.name'></td>
        <td v-text='file.size'></td>
        <td v-text='file.progress'></td>
        <td v-text='onStatus(file)'></td>
        <td>
          <button type='button' value='upload' @click="uploadItem(file)">上传</button>
        </td>
      </tr>
      </tbody>
    </table>
    <button type='button' @click="uploadAll">上传所有文件</button>
  </vue-file-upload>
</template>
<style>
</style>
<script>
  import VueFileUpload from 'vue-file-upload';
  export default{
    data(){
      return{
        files:[],
        //文件过滤器，只能上传图片
        filters:[
          {
            name:"imageFilter",
            fn(file){
              var type = '|' + file.type.slice(file.type.lastIndexOf('/') + 1) + '|';
              return '|jpg|png|jpeg|bmp|gif|'.indexOf(type) !== -1;
            }
          }
        ],
        //回调函数绑定
        cbEvents:{
          onCompleteUpload:(file,response,status,header)=>{
          console.log(file);
      console.log("finish upload;")
    }
    },
      //xhr请求附带参数
      reqopts:{
        formData:{
          tokens:'tttttttttttttt'
        },
        responseType:'json',
          withCredentials:false
      }
    }
    },
    methods:{
      onStatus(file){
        if(file.isSuccess){
          return "上传成功";
        }else if(file.isError){
          return "上传失败";
        }else if(file.isUploading){
          return "正在上传";
        }else{
          return "待上传";
        }
      },
      uploadItem(file){
        //单个文件上传
        file.upload();
      },
      uploadAll(){
        //上传所有文件
        this.$broadcast('DO_POST_FILE');
      }
    },
    components:{
      VueFileUpload
    }
  }
</script>
`

在实际过程中是这样使用的

`<template>
  <div class="container-fluid">
    <form class="form-horizontal" action="/res/v1/people"
          enctype="multipart/form-data" method="post">
      another form
    </form>
    <images-uploader></images-uploader>

  </div>
</template>
<style>

</style>
<script>
  import ImagesUploader from './ImagesUploader.vue'

  export default{
    data(){
      return {
        msg: 'hello vue'
      }
    },
    components: {
      'images-uploader': ImagesUploader,
    },
  }
</script>
`

但渲染出来的结果，却只有一个绿色的按钮。可以通过这个input插入图片，但插入后浏览器没有任何动作，既看不到控制台有error，也看不到后台有网络传输。实际上应该渲染出来的table也没看见。我debug也可以进入到“return '|jpg|png|jpeg|bmp|gif|'.indexOf(type) !== -1;” 但之后就没有下文了。请帮我看看哪里有问题。
浏览器环境： Chrome Version 51.0.2704.63

**Comment by marchFantasy** [comment]
@magicliang ，前端需要用到webpackl和vue-loader
最好用线上环境给我看演示代码，例如：[jsfiddle](https://jsfiddle.net/),[codepen](http://codepen.io/)

**Comment by magicliang** [comment]
我是直接用最新版的 vue-cli 打出来的 webpack 风格的项目。我也仔细检查过，没有 module no resolve 的情况。 我是有想过发一些在线runtime的环境，可在线runtime的环境可以支持webpack和vue么，和我直接发.vue文件恐怕没有区别。

如果你可以快速浏览一下这两个vue，说不定可以告诉我哪里缺少配置或者api。

**Comment by marchFantasy** [comment]
@magicliang ,我给你的模板有问题，改好了

**Comment by magicliang** [comment]
原来不能中段 yield 其他标签啊，我明白了。
谢谢。
