### ISSUE TITLE
IE浏览器下上传图片异常

### ISSUE THREAD

**Issue by webfanrc** [marchFantasy/vue-file-upload#90]
1. 操作系统类型(os)：windows
2. 浏览器类型(browser)：IE；版本号(version)：11
3. 问题错误信息(error stacks)：上传成功后图片显示一下，然后会自己自动删除，导致回显的list没有图片

**Comment by marchFantasy** [comment]
你测试的是我提供的demo吗？我的demo在ie11下是没问题的

**Comment by webfanrc** [comment]
经过排查，发现问题在于IE中response为string，导致之后的正常判断逻辑没通过。目前修改见图：
![e734531e-5d59-4eeb-99ff-b84bed534f80](https://user-images.githubusercontent.com/22745312/49979373-b65dc080-ff89-11e8-8afc-41985eb5aa31.png)
