### ISSUE TITLE
文件上传之前的事件, onBeforeUpload， 不能进行文件的拦截.

### ISSUE THREAD

**Issue by tuotuogenjudi** [marchFantasy/vue-file-upload#91]
多文件上传，想在文件上传之前进行文件校验，如果大于500M直接报错，不想触发上传，其他正常文件正常上传，在onBeforeUpload:(file) => { return false; }  中拦截不起作用。 @marchFantasy

**Comment by marchFantasy** [comment]
可以在filters函数里过滤，并给出提示；onBeforeUpload不具备取消上传的功能
